// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    district_health_snapshot: {
        name: "district_health_snapshot";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state_ut: string;
          /** @sqlType DOUBLE */
          households_surveyed: number;
          /** @sqlType DOUBLE */
          women_15_49_interviewed: number;
          /** @sqlType DOUBLE */
          men_15_54_interviewed: number;
          /** @sqlType DOUBLE */
          female_population_age_6_years_and_above_ever_schooled_pct: number;
          /** @sqlType DOUBLE */
          population_below_age_15_years_pct: number;
          /** @sqlType DOUBLE */
          sex_ratio_total_f_per_1000_m: number;
          /** @sqlType STRING */
          sex_ratio_at_birth_5y_f_per_1000_m: string;
          /** @sqlType DOUBLE */
          child_u5_whose_birth_was_civil_reg_pct: number;
          /** @sqlType STRING */
          deaths_in_the_last_3_years_civil_reg_pct: string;
          /** @sqlType DOUBLE */
          hh_electricity_pct: number;
          /** @sqlType DOUBLE */
          hh_improved_water_pct: number;
          /** @sqlType DOUBLE */
          hh_use_improved_sanitation_pct: number;
          /** @sqlType DOUBLE */
          households_using_clean_fuel_for_cooking_pct: number;
          /** @sqlType DOUBLE */
          households_using_iodized_salt_pct: number;
          /** @sqlType DOUBLE */
          hh_member_covered_health_insurance_pct: number;
          /** @sqlType STRING */
          child_5y_who_attended_pre_primary_school_during_the_school_pct: string;
          /** @sqlType DOUBLE */
          women_age_15_49_who_are_literate_pct: number;
          /** @sqlType DOUBLE */
          women_age_15_49_with_10_or_more_years_of_schooling_pct: number;
          /** @sqlType STRING */
          w20_24_married_before_age_18_years_pct: string;
          /** @sqlType STRING */
          births_in_the_5_years_preceding_the_survey_that_are_birth_3_pct: string;
          /** @sqlType STRING */
          w15_19_who_were_already_mothers_or_pregnant_at_the_time_of_pct: string;
          /** @sqlType DOUBLE */
          w15_24_who_use_menstrual_hygiene_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_any_method_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_modern_method_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_f_steril_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_m_steril_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_iud_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_pill_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_condom_pct: number;
          /** @sqlType DOUBLE */
          fp_cm_w15_49_injectables_pct: number;
          /** @sqlType DOUBLE */
          fp_unmet_total_cm_w15_49_7_pct: number;
          /** @sqlType DOUBLE */
          fp_unmet_spacing_cm_w15_49_7_pct: number;
          /** @sqlType DOUBLE */
          health_worker_ever_talked_to_female_non_users_about_family_pct: number;
          /** @sqlType STRING */
          current_users_ever_told_about_side_effects_of_current_metho_pct: string;
          /** @sqlType STRING */
          mothers_who_had_an_anc_visit_in_the_first_trimester_lb5y_pct: string;
          /** @sqlType STRING */
          mothers_who_had_at_least_4_anc_visits_lb5y_pct: string;
          /** @sqlType STRING */
          mothers_whose_last_birth_was_protected_against_neo_tetanus_pct: string;
          /** @sqlType STRING */
          mothers_who_consumed_ifa_for_100_days_or_more_when_they_wer_pct: string;
          /** @sqlType STRING */
          mothers_who_consumed_ifa_for_180_days_or_more_when_they_wer_pct: string;
          /** @sqlType STRING */
          registered_pregnancies_for_which_the_mother_received_a_mcp_pct: string;
          /** @sqlType STRING */
          mothers_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwif_pct: string;
          /** @sqlType STRING */
          average_out_of_pocket_expenditure_per_delivery_in_a_public_fac: string;
          /** @sqlType STRING */
          children_born_at_home_who_were_taken_to_a_health_facility_f_pct: string;
          /** @sqlType STRING */
          children_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwi_pct: string;
          /** @sqlType DOUBLE */
          institutional_birth_5y_pct: number;
          /** @sqlType DOUBLE */
          institutional_birth_in_public_facility_5y_pct: number;
          /** @sqlType DOUBLE */
          home_birth_that_were_conducted_by_skilled_hp_5y_10_pct: number;
          /** @sqlType DOUBLE */
          births_attended_by_skilled_hp_5y_10_pct: number;
          /** @sqlType DOUBLE */
          births_delivered_by_csection_5y_pct: number;
          /** @sqlType STRING */
          births_in_a_private_fac_that_were_delivered_by_csection_5y_pct: string;
          /** @sqlType STRING */
          births_in_a_public_fac_that_were_delivered_by_csection_5y_pct: string;
          /** @sqlType STRING */
          child_12_23m_fully_vaccinated_based_on_information_from_eit_pct: string;
          /** @sqlType STRING */
          child_12_23m_fully_vaccinated_based_on_information_from_vax_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_have_received_bcg_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_have_received_3_doses_of_polio_vaccine_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_have_received_3_doses_of_penta_or_dpt_vacc_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_have_received_the_first_dose_of_mcv_mcv_pct: string;
          /** @sqlType STRING */
          child_24_35m_who_have_received_a_second_dose_of_mcv_mcv_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_have_received_3_doses_of_rotavirus_vaccine_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_have_received_3_doses_of_penta_or_hepatiti_pct: string;
          /** @sqlType STRING */
          child_9_35m_who_received_a_vit_a_in_the_last_6_months_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_received_most_of_their_vaccinations_in_a_p_pct: string;
          /** @sqlType STRING */
          child_12_23m_who_received_most_of_their_vaccinations_in_a_2_pct: string;
          /** @sqlType DOUBLE */
          prev_diarrhoea_2wk_child_u5_pct: number;
          /** @sqlType STRING */
          children_with_diarrhoea_2wk_who_received_oral_rehydration_s_pct: string;
          /** @sqlType STRING */
          children_with_diarrhoea_2wk_who_received_zinc_child_u5_pct: string;
          /** @sqlType STRING */
          children_with_diarrhoea_2wk_taken_to_a_health_facility_or_h_pct: string;
          /** @sqlType DOUBLE */
          children_prev_symptoms_of_acute_respiratory_infection_ari_2_pct: number;
          /** @sqlType STRING */
          children_with_fever_or_symptoms_of_ari_2wk_taken_to_a_healt_pct: string;
          /** @sqlType STRING */
          children_under_age_3_years_breastfed_within_one_hour_of_bir_pct: string;
          /** @sqlType STRING */
          child_u6m_exclusively_breastfed_pct: string;
          /** @sqlType STRING */
          child_6_8m_receiving_solid_or_semi_solid_food_and_breastmil_pct: string;
          /** @sqlType STRING */
          breastfeeding_child_6_23m_receiving_an_adequate_diet16_17_pct: string;
          /** @sqlType STRING */
          non_breastfeeding_child_6_23m_receiving_an_adequate_diet16_pct: string;
          /** @sqlType STRING */
          total_child_6_23m_receiving_an_adequate_diet16_17_pct: string;
          /** @sqlType STRING */
          child_u5_who_are_stunted_height_for_age_18_pct: string;
          /** @sqlType STRING */
          child_u5_who_are_wasted_weight_for_height_18_pct: string;
          /** @sqlType STRING */
          child_u5_who_are_severe_wasted_weight_for_height_19_pct: string;
          /** @sqlType STRING */
          child_u5_who_are_underweight_weight_for_age_18_pct: string;
          /** @sqlType STRING */
          child_u5_who_are_overweight_weight_for_height_20_pct: string;
          /** @sqlType DOUBLE */
          women_age_15_49_years_whose_bmi_bmi_is_underweight_bmi_lt_1_pct: number;
          /** @sqlType DOUBLE */
          women_age_15_49_years_who_are_overweight_obese_bmi_gte_25_0_pct: number;
          /** @sqlType DOUBLE */
          women_age_15_49_years_who_have_high_risk_whr_gte_0_85_pct: number;
          /** @sqlType STRING */
          child_6_59m_who_are_anaemic_lt_11_0_g_dl_22_pct: string;
          /** @sqlType DOUBLE */
          non_pregnant_w15_49_who_are_anaemic_lt_12_0_g_dl_22_pct: number;
          /** @sqlType STRING */
          pregnant_w15_49_who_are_anaemic_lt_11_0_g_dl_22_pct: string;
          /** @sqlType DOUBLE */
          all_w15_49_who_are_anaemic_pct: number;
          /** @sqlType STRING */
          all_w15_19_who_are_anaemic_pct: string;
          /** @sqlType DOUBLE */
          women_age_15_years_and_above_with_high_141_160_mg_dl_blood_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_with_very_high_gt_160_mg_dl_blood_sugar_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_with_high_or_very_high_gt_140_mg_dl_blood_sugar_or_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_with_high_141_160_mg_dl_blood_sugar_pct: number;
          /** @sqlType DOUBLE */
          men_age_15_years_and_above_with_very_high_gt_160_mg_dl_bloo_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_with_high_or_very_high_gt_140_mg_dl_blood_sugar_or_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_with_mildly_high_bp_sys_140_159_mmhg_and_or_dia_90_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_with_moderately_or_severely_high_bp_sys_gte_160_mm_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_with_high_bp_sys_gte_140_mmhg_and_or_dia_gte_90_mm_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_with_mildly_high_bp_sys_140_159_mmhg_and_or_dia_90_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_with_moderately_or_severely_high_bp_sys_gte_160_mm_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_with_high_bp_sys_gte_140_mmhg_and_or_dia_gte_90_mm_pct: number;
          /** @sqlType DOUBLE */
          women_age_30_49_years_ever_undergone_a_cervical_screen_pct: number;
          /** @sqlType DOUBLE */
          women_age_30_49_years_ever_undergone_a_breast_exam_pct: number;
          /** @sqlType DOUBLE */
          women_age_30_49_years_ever_undergone_an_oral_cancer_exam_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_who_use_any_kind_of_tobacco_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_who_use_any_kind_of_tobacco_pct: number;
          /** @sqlType DOUBLE */
          w15_plus_who_consume_alcohol_pct: number;
          /** @sqlType DOUBLE */
          m15_plus_who_consume_alcohol_pct: number;
        }>;
      };
    facilities_snapshot: {
        name: "facilities_snapshot";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          source_types: string;
          /** @sqlType STRING */
          source_ids: string;
          /** @sqlType STRING */
          source_content_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          organization_type: string;
          /** @sqlType STRING */
          content_table_id: string;
          /** @sqlType STRING */
          phone_numbers: string;
          /** @sqlType STRING */
          officialPhone: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          websites: string;
          /** @sqlType STRING */
          officialWebsite: string;
          /** @sqlType STRING */
          yearEstablished: string;
          /** @sqlType STRING */
          acceptsVolunteers: string;
          /** @sqlType STRING */
          facebookLink: string;
          /** @sqlType STRING */
          address_line1: string;
          /** @sqlType STRING */
          address_line2: string;
          /** @sqlType STRING */
          address_line3: string;
          /** @sqlType STRING */
          address_city: string;
          /** @sqlType STRING */
          address_stateOrRegion: string;
          /** @sqlType STRING */
          address_zipOrPostcode: string;
          /** @sqlType STRING */
          address_country: string;
          /** @sqlType STRING */
          address_countryCode: string;
          /** @sqlType STRING */
          countries: string;
          /** @sqlType STRING */
          facilityTypeId: string;
          /** @sqlType STRING */
          operatorTypeId: string;
          /** @sqlType STRING */
          affiliationTypeIds: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          area: string;
          /** @sqlType STRING */
          numberDoctors: string;
          /** @sqlType STRING */
          capacity: string;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType STRING */
          procedure: string;
          /** @sqlType STRING */
          equipment: string;
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          recency_of_page_update: string;
          /** @sqlType STRING */
          distinct_social_media_presence_count: string;
          /** @sqlType STRING */
          affiliated_staff_presence: string;
          /** @sqlType STRING */
          custom_logo_presence: string;
          /** @sqlType STRING */
          number_of_facts_about_the_organization: string;
          /** @sqlType STRING */
          post_metrics_most_recent_social_media_post_date: string;
          /** @sqlType STRING */
          post_metrics_post_count: string;
          /** @sqlType STRING */
          engagement_metrics_n_followers: string;
          /** @sqlType STRING */
          engagement_metrics_n_likes: string;
          /** @sqlType STRING */
          engagement_metrics_n_engagements: string;
          /** @sqlType STRING */
          source: string;
          /** @sqlType STRING */
          coordinates: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          cluster_id: string;
          /** @sqlType STRING */
          source_urls: string;
        }>;
      };
    pincode_snapshot: {
        name: "pincode_snapshot";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          circlename: string;
          /** @sqlType STRING */
          regionname: string;
          /** @sqlType STRING */
          divisionname: string;
          /** @sqlType STRING */
          officename: string;
          /** @sqlType BIGINT */
          pincode: number;
          /** @sqlType STRING */
          officetype: string;
          /** @sqlType STRING */
          delivery: string;
          /** @sqlType STRING */
          district: string;
          /** @sqlType STRING */
          statename: string;
          /** @sqlType STRING */
          latitude: string;
          /** @sqlType STRING */
          longitude: string;
        }>;
      };
  }
}
